In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

pd.set_option('display.max_columns', None)

In [7]:
df = pd.read_csv('/Users/jjburrell/Econometrics/Econometrics/MSR Prep/sample_school_curriculum_data.csv')

In [11]:
df.sample(n=20).head()

,school_id,school_name,district_id,district_name,year,date_submitted,subject_changed,avg_math_score,avg_income_2005,avg_income_2015
1004,51,School_51,12,District_12,2004,NaN,none,55.111494,56274.161971,58490.064226
704,36,School_36,8,District_8,2004,NaN,none,68.824440,66139.477833,70675.282047
411,21,School_21,10,District_10,2011,NaN,none,61.941922,64340.480349,64556.172755
307,16,School_16,4,District_4,2007,NaN,none,70.240492,72184.238851,60919.759245
1720,87,School_87,2,District_2,2000,NaN,none,78.071392,58893.885591,59871.688797

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   school_id        2000 non-null   int64
 1   school_name      2000 non-null   object
 2   district_id      2000 non-null   int64
 3   district_name    2000 non-null   object
 4   year             2000 non-null   int64
 5   date_submitted   89 non-null     float64
 6   subject_changed  2000 non-null   object
 7   avg_math_score   2000 non-null   float64
 8   avg_income_2005  2000 non-null   float64
 9   avg_income_2015  2000 non-null   float64
dtypes: float64(4), int64(3), object(3)
memory usage: 156.4+ KB

In [13]:
df.dropna()

,school_id,school_name,district_id,district_name,year,date_submitted,subject_changed,avg_math_score,avg_income_2005,avg_income_2015
9,1,School_1,4,District_4,2009,1.243814e+18,math,77.117987,72184.238851,60919.759245
55,3,School_3,15,District_15,2015,1.433117e+18,math,69.423899,46200.657340,67083.062502
74,4,School_4,12,District_12,2014,1.401581e+18,math,67.152588,56274.161971,58490.064226
87,5,School_5,7,District_7,2007,1.180656e+18,math,74.050634,72633.702524,67742.236995
108,6,School_6,12,District_12,2008,1.212278e+18,math,75.247898,56274.161971,58490.064226
...,...,...,...,...,...,...,...,...,...,...
1893,95,School_95,12,District_12,2013,1.370045e+18,math,71.022655,56274.161971,58490.064226
1907,96,School_96,8,District_8,2007,1.180656e+18,math,70.012247,66139.477833,70675.282047
1927,97,School_97,6,District_6,2007,1.180656e+18,math,70.288355,58126.904344,84656.487689
1971,99,School_99,3,District_3,2011,1.306886e+18,math,73.921425,65181.508305,73142.473326
1988,100,School_100,1,District_1,2008,1.212278e+18,math,76.801472,63973.713224,64377.124708

In [16]:
df.isnull().sum()

school_id             0
school_name           0
district_id           0
district_name         0
year                  0
date_submitted     1911
subject_changed       0
avg_math_score        0
avg_income_2005       0
avg_income_2015       0
dtype: int64

In [17]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
school_id,2000.0,5.050000e+01,2.887329e+01,1.000000e+00,2.575000e+01,5.050000e+01,7.525000e+01,1.000000e+02
district_id,2000.0,8.420000e+00,4.330471e+00,1.000000e+00,5.000000e+00,8.000000e+00,1.200000e+01,1.500000e+01
year,2000.0,2.009500e+03,5.767723e+00,2.000000e+03,2.004750e+03,2.009500e+03,2.014250e+03,2.019000e+03
date_submitted,89.0,1.269331e+18,9.012474e+16,1.117584e+18,1.180656e+18,1.275350e+18,1.338509e+18,1.433117e+18
avg_math_score,2000.0,7.002769e+01,5.418380e+00,5.446138e+01,6.641288e+01,6.980455e+01,7.345974e+01,8.872313e+01
avg_income_2005,2000.0,5.998310e+04,7.891392e+03,4.469376e+04,5.627416e+04,5.889389e+04,6.518151e+04,7.263370e+04
avg_income_2015,2000.0,6.557731e+04,6.819346e+03,5.575252e+04,5.987169e+04,6.455617e+04,7.067528e+04,8.465649e+04

In [18]:
df.describe()

,school_id,district_id,year,date_submitted,avg_math_score,avg_income_2005,avg_income_2015
count,2000.000000,2000.000000,2000.000000,8.900000e+01,2000.000000,2000.000000,2000.000000
mean,50.500000,8.420000,2009.500000,1.269331e+18,70.027692,59983.099008,65577.312729
std,28.873289,4.330471,5.767723,9.012474e+16,5.418380,7891.391827,6819.346194
min,1.000000,1.000000,2000.000000,1.117584e+18,54.461384,44693.758043,55752.518138
25%,25.750000,5.000000,2004.750000,1.180656e+18,66.412876,56274.161971,59871.688797
50%,50.500000,8.000000,2009.500000,1.275350e+18,69.804548,58893.885591,64556.172755
75%,75.250000,12.000000,2014.250000,1.338509e+18,73.459736,65181.508305,70675.282047
max,100.000000,15.000000,2019.000000,1.433117e+18,88.723129,72633.702524,84656.487689

In [21]:
df = df.drop_duplicates()
df.dropna(subset=['school_id', 'district_id'])

,school_id,school_name,district_id,district_name,year,date_submitted,subject_changed,avg_math_score,avg_income_2005,avg_income_2015
0,1,School_1,4,District_4,2000,NaN,none,74.363718,72184.238851,60919.759245
1,1,School_1,4,District_4,2001,NaN,none,74.593195,72184.238851,60919.759245
2,1,School_1,4,District_4,2002,NaN,none,75.544552,72184.238851,60919.759245
3,1,School_1,4,District_4,2003,NaN,none,79.492041,72184.238851,60919.759245
4,1,School_1,4,District_4,2004,NaN,none,73.427224,72184.238851,60919.759245
...,...,...,...,...,...,...,...,...,...,...
1995,100,School_100,1,District_1,2015,NaN,none,75.236499,63973.713224,64377.124708
1996,100,School_100,1,District_1,2016,NaN,none,74.383574,63973.713224,64377.124708
1997,100,School_100,1,District_1,2017,NaN,none,76.124847,63973.713224,64377.124708
1998,100,School_100,1,District_1,2018,NaN,none,72.845924,63973.713224,64377.124708
1999,100,School_100,1,District_1,2019,NaN,none,72.573154,63973.713224,64377.124708

In [5]:
df = pd.read_csv('/Users/jjburrell/Econometrics/Econometrics/MSR Prep/sample_school_curriculum_data.csv')
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   school_id        2000 non-null   int64
 1   school_name      2000 non-null   object
 2   district_id      2000 non-null   int64
 3   district_name    2000 non-null   object
 4   year             2000 non-null   int64
 5   date_submitted   89 non-null     float64
 6   subject_changed  2000 non-null   object
 7   avg_math_score   2000 non-null   float64
 8   avg_income_2005  2000 non-null   float64
 9   avg_income_2015  2000 non-null   float64
dtypes: float64(4), int64(3), object(3)
memory usage: 156.4+ KB

,school_id,district_id,year,date_submitted,avg_math_score,avg_income_2005,avg_income_2015
count,2000.000000,2000.000000,2000.000000,8.900000e+01,2000.000000,2000.000000,2000.000000
mean,50.500000,8.420000,2009.500000,1.269331e+18,70.027692,59983.099008,65577.312729
std,28.873289,4.330471,5.767723,9.012474e+16,5.418380,7891.391827,6819.346194
min,1.000000,1.000000,2000.000000,1.117584e+18,54.461384,44693.758043,55752.518138
25%,25.750000,5.000000,2004.750000,1.180656e+18,66.412876,56274.161971,59871.688797
50%,50.500000,8.000000,2009.500000,1.275350e+18,69.804548,58893.885591,64556.172755
75%,75.250000,12.000000,2014.250000,1.338509e+18,73.459736,65181.508305,70675.282047
max,100.000000,15.000000,2019.000000,1.433117e+18,88.723129,72633.702524,84656.487689

In [6]:
df['date_submitted'] = pd.to_datetime(df['date_submitted'])
df['year'] = df['date_submitted'].dt.year